package Main;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Main.HomePage;
import Main.Staff;
import Main.Product;
import Main.Department;
import Main.Transaction;
import Main.Vendors;
import Main.Main;

public class HomePage extends javax.swing.JFrame {


//Loading the UI    
    public HomePage() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
 
    
    //Swing generated code
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        quitbutton = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        productbutton = new javax.swing.JButton();
        vendorsbutton = new javax.swing.JButton();
        transactionbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jobsbutton = new javax.swing.JButton();
        staffbutton = new javax.swing.JButton();
        departmentbutton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gaming Peripheral Store");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gaming Peripheral Store");

        quitbutton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        quitbutton.setText("Quit");
        quitbutton.setFocusable(false);
        quitbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quitbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitbutton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to our store!");
        jToolBar1.add(jLabel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        productbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        productbutton.setText("Product");
        productbutton.setFocusable(false);
        productbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        productbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        productbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productbuttonActionPerformed(evt);
            }
        });

        vendorsbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vendorsbutton.setText("Vendors");
        vendorsbutton.setFocusable(false);
        vendorsbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vendorsbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        vendorsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorsbuttonActionPerformed(evt);
            }
        });

        transactionbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        transactionbutton.setText("Transaction");
        transactionbutton.setFocusable(false);
        transactionbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transactionbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transactionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vendorsbutton)
                    .addComponent(productbutton))
                .addGap(460, 460, 460))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(productbutton)
                .addGap(38, 38, 38)
                .addComponent(vendorsbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(transactionbutton)
                .addGap(25, 25, 25))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jobsbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jobsbutton.setText("Jobs");
        jobsbutton.setFocusable(false);
        jobsbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jobsbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jobsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobsbuttonActionPerformed(evt);
            }
        });

        staffbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        staffbutton.setText("Staff");
        staffbutton.setFocusable(false);
        staffbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        staffbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffbuttonActionPerformed(evt);
            }
        });

        departmentbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        departmentbutton.setText("Department");
        departmentbutton.setFocusable(false);
        departmentbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        departmentbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        departmentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffbutton)
                    .addComponent(jobsbutton)
                    .addComponent(departmentbutton))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jobsbutton)
                .addGap(36, 36, 36)
                .addComponent(staffbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(departmentbutton)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productbuttonActionPerformed
        Product productpage = new Product();
        productpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_productbuttonActionPerformed

    private void vendorsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorsbuttonActionPerformed
        Vendors vendorpage = new Vendors();
        vendorpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_vendorsbuttonActionPerformed

    private void transactionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionbuttonActionPerformed
        Transaction transactionpage = new Transaction();
        transactionpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_transactionbuttonActionPerformed

    private void staffbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffbuttonActionPerformed
        Staff staffpage = new Staff();
        staffpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_staffbuttonActionPerformed

    private void departmentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentbuttonActionPerformed
        Department departmentpage = new Department();
        departmentpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_departmentbuttonActionPerformed

    private void jobsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobsbuttonActionPerformed
        Jobs jobspage = new Jobs();
        jobspage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jobsbuttonActionPerformed

    private void quitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitbuttonActionPerformed
    dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_quitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton departmentbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jobsbutton;
    private javax.swing.JButton productbutton;
    private javax.swing.JButton quitbutton;
    private javax.swing.JButton staffbutton;
    private javax.swing.JButton transactionbutton;
    private javax.swing.JButton vendorsbutton;
    // End of variables declaration//GEN-END:variables
}
